version: '3.1'

services:

  website:
    container_name: website
    build:
      context: .
    ports:
      - 8000:8000
    command: ["python3.8", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
    volumes:
      - .:/code